### ISSUE TITLE
8_queens.py simplification

### ISSUE THREAD

**Issue by charlieweinberger** [nathan-create/machine-learning#1]
In your 8_queens.py code, you can simplify your same_row(), same_column(), and same_diagonal() methods. Instead of having `    if point1[0] == point2[0]:
        return True
    else:
        return False`, you can have `return point1[0] == point2[0]`. If the equation is true, `point1[0] == point2[0]` will equal `True`, so it will return `True`. You can apply this to same_column and same_diagonal.

**Comment by nathan-create** [comment]
I added the simplification to both the row and col function, but I left the diag the same so I dont have the chance to mess it up, as it checks two different equivalencies instead of 1, like row and col.
