### ISSUE TITLE
8_queens.py long, hard-to-read line

### ISSUE THREAD

**Issue by charlieweinberger** [nathan-create/machine-learning#2]
Line 46 of your 8_queens.py code is very long. You can break it up to make it more clear. For example, you could change it so that before the if statement, you have `is_same_row = same_row(locations[point1], locations[point2])`, `is_same_column = same_column(locations[point1], locations[point2])`, and `is_same_diagonal = same_diagnol(locations[point1], locations[point2])`. Then, the if statement is `if is_same_row or is_same_column or is_same_diagonal:`. This is more simple and easier to read.

**Comment by nathan-create** [comment]
I have changed the line so that the same_row, same_col, and same_diag check are set to variables in turn making line 46 shorter.
